### ISSUE TITLE
Storing conditions in Database

### ISSUE THREAD

**Issue by rahil471** [DeadAlready/easy-rbac#5]
I came from your awesome blog post! I have implemented exactly a similar RBAC in one of  my projects, however, it does not include the conditional part of it. 
My question to you is how can we store those conditions in Database? 

I also have another one: What would you suggest if I want Porperty/Role based access control: 
For eg: Suppose I have a user property as `location`! Now I want to give `Admin` set of privileges to Mr.x but only on other users belonging to his same location.  So Mr. x can modify/delete users only belonging in his location. 
I think it can be done using the condition part but would like to hear what you have to say.

Hope I'm clear.

**Comment by DeadAlready** [comment]
You could stringify the conditional functions and then store them as strings. However I must note that storing functions in the database like that is not really the best of ideas: mainly because it means your codebase is now scattered between files and the database making error tracking more difficult. And secondly it provides attackers with a privilege escalation point.

The optimal approach is more dependent on your actual needs, but usually I still recommend having the conditional parts in the codebase and then if you do need to switch around the conditional statements you can make the original conditional ask the database for the actual conditional to check (get the function name and run it).

If I understand correctly your second part then you would probably have a hierarchy like 
Admin->LocationAdmin->User
The LocationAdmin's conditionals duplicate the needed admin privileges with a location check against the target.location. If the condition passes they have admin privilege if not then they don't.
